http {
    upstream backend {
        server :8080;
        server :8080;
        # server 192.0.0.1 backup;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }
}   