http {
    upstream backend {
        server ser1:8080;
        server ser2:8080;
        server ser3:8080;
        # server 192.0.0.1 backup;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}   